### ISSUE TITLE
Flatpak does not run

### ISSUE THREAD

**Issue by Silejonu** [Sebicodes99/pleaserunthat-beta#11]
On Fedora 38, up-to-date:

```bash
$ flatpak run 'io.github.Sebicodes99.Prt'
Traceback (most recent call last):
  File "/app/bin/app.py", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by Sebicodes99** [comment]
Hello, The problem was the runtime, We are currently fixing bugs for compatibility in all machines, Thanks for trying the app!

**Comment by Sebicodes99** [comment]
Now, We're working on an update that should fix that.

**Comment by Sebicodes99** [comment]
Check the new update out, it should have solved the issue.

**Comment by potter-jason** [comment]
applied the update, no more error. Get the GUI now and selected Server. Asks for ip address and port. Is this the server ip address i want to have the cliennts connect to?

**Comment by Sebicodes99** [comment]
yes

**Comment by Sebicodes99** [comment]
also, the port should be the same as client.

**Comment by Sebicodes99** [comment]
If you get a invalid address error, it's because the port is in use.

**Comment by potter-jason** [comment]
ok, entered ip address and port...I was confused for amoment because after clicking start nothing happened. But in terminal it says waiting for connection on the IP:Port. You may want to add some sort of notification in the little GUI the server is listening.

I was able to connect..I think. I point a browser at the IP:Port. Nothing in the browser window indicating a connection, but again inthe terminal says there is a connection from the client ip. 

What the process to connect?

**Comment by Sebicodes99** [comment]
Thanks for your idea. For connecting, in other computer (or window of the app) choose client and introduce the  IP Address and port of the server and click connect.

**Comment by potter-jason** [comment]
ah ok, you need Prt on both client and server...makes sense....trying now.

**Comment by Sebicodes99** [comment]
Will be added in next update!

**Comment by Sebicodes99** [comment]
> ah ok, you need Prt on both client and server...makes sense....trying now.

Yes!

**Comment by Sebicodes99** [comment]
Thanks for trying the app, It motivates and helps me to keep working on the app.

**Comment by Sebicodes99** [comment]
> ok, entered ip address and port...I was confused for amoment because after clicking start nothing happened. But in terminal it says waiting for connection on the IP:Port. You may want to add some sort of notification in the little GUI the server is listening.
> 
> I was able to connect..I think. I point a browser at the IP:Port. Nothing in the browser window indicating a connection, but again inthe terminal says there is a connection from the client ip.
> 
> What the process to connect?

Already added that, will be released in the next version!

**Comment by Sebicodes99** [comment]
Feature released! Also, now it will tell you if the server receives something
