### ISSUE TITLE
Please remove this from flathub and destroy it with fire

### ISSUE THREAD

**Issue by michaelmrose** [Sebicodes99/pleaserunthat-beta#16]
This will only ever be used for malware and exposes users to having their PC remote-controlled by a stranger looking for idiots running this. Based on a brief review, this runs ANYTHING an unauthenticated user sends, meaning it could as easily run malware from strangers even when the party prompting you to use this has good intentions.

Users should use something like Teamviewer or ssh, which already exists and have proper authentication.

**Comment by Sebicodes99** [comment]
Hello, The app is in BETA so you should expect everything to be implemented also, unless you have open ports, no one outside your network can do anything.
